Id: Giorgiotani.Peazip
Name: peazip
AppMoniker: peazip
Version: 7.4.0
Publisher: Giorgio Tani
Author: Giorgio Tani
License: Open Source license LGPLv3
LicenseUrl: https://peazip.github.io/peazip-tos-privacy.html#software_copyright
MinOSVersion: 10.0.0.0
Homepage: https://peazip.github.io
Tags: "zip, compression, peazip, giorgio, tani, files, compressed"
InstallerType: exe

# ======================= Installers  ================== 

Installers: 
  - Arch: x64
    Url: https://github.com/peazip/PeaZip/releases/download/7.4.0/peazip-7.4.0.WIN64.exe
    Sha256: BD700CFBC7D7E3F696115EA6DDA18044BEC32E94C34B731EFF9190747257FC73
    Language: en-US
    Switches: 
      Silent: "/SILENT /NORESTART"
      SilentWithProgress: "/VERYSILENT /NORESTART"
