Id: Giorgiotani.Peazip
Name: peazip
AppMoniker: peazip
Version: 7.6.0
Publisher: Giorgio Tani
Author: Giorgio Tani
License: Open Source license LGPLv3
LicenseUrl: https://peazip.github.io/peazip-tos-privacy.html#software_copyright
MinOSVersion: 10.0.0.0
Homepage: https://peazip.github.io
Tags: "zip, compression, peazip, giorgio, tani, files, compressed"
InstallerType: exe

# ======================= Installers  ================== 

Installers: 
  - Arch: x64
    Url: https://github.com/peazip/PeaZip/releases/download/7.6.0/peazip-7.6.0.WIN64.exe
    Sha256: DE09293CBBF45382B8BE9EE6244545D22B4EF64E2B7AC3B9DCC9AB1BE7FA1B3B
    Language: en-US
    Switches: 
      Silent: "/SILENT /NORESTART"
      SilentWithProgress: "/VERYSILENT /NORESTART"
